import { AnalysisDocument } from '@/types/index';

export const dummyAnalysisData: AnalysisDocument = {
  publicId: 'demo-taste-001',
  user: {
    spotifyId: 'spotify123',
    displayName: 'Luna Starlight',
    email: 'luna@example.com',
    followers: 2847,
    images: [
      {
        url: 'https://i.pravatar.cc/150?img=23',
        height: 150,
        width: 150,
      },
    ],
  },
  data: {
    user: {
      spotifyId: 'spotify123',
      displayName: 'Luna Starlight',
      email: 'luna@example.com',
      followers: 2847,
      images: [
        {
          url: 'https://i.pravatar.cc/150?img=23',
          height: 150,
          width: 150,
        },
      ],
    },
    topTracks: {
      shortTerm: [
        {
          id: 'track1',
          name: 'Midnight Dreams',
          artists: [
            {
              id: 'artist1',
              name: 'Crystal Waves',
              genres: ['synthwave', 'electronic'],
              popularity: 78,
              images: [],
              followers: { total: 125000 },
              external_urls: { spotify: 'https://open.spotify.com/artist/artist1' },
            },
          ],
          album: {
            id: 'album1',
            name: 'Neon Visions',
            images: [],
            release_date: '2024-01-15',
            total_tracks: 12,
          },
          duration_ms: 234000,
          explicit: false,
          popularity: 84,
          preview_url: null,
          external_urls: { spotify: 'https://open.spotify.com/track/track1' },
        },
        {
          id: 'track2',
          name: 'Digital Hearts',
          artists: [
            {
              id: 'artist2',
              name: 'Neon Pulse',
              genres: ['electronic', 'indie'],
              popularity: 72,
              images: [],
              followers: { total: 98000 },
              external_urls: { spotify: 'https://open.spotify.com/artist/artist2' },
            },
          ],
          album: {
            id: 'album2',
            name: 'Electric Dreams',
            images: [],
            release_date: '2023-11-20',
            total_tracks: 10,
          },
          duration_ms: 198000,
          explicit: false,
          popularity: 81,
          preview_url: null,
          external_urls: { spotify: 'https://open.spotify.com/track/track2' },
        },
        {
          id: 'track3',
          name: 'Cosmic Waves',
          artists: [
            {
              id: 'artist3',
              name: 'Aurora Sky',
              genres: ['ambient', 'synthwave'],
              popularity: 68,
              images: [],
              followers: { total: 67000 },
              external_urls: { spotify: 'https://open.spotify.com/artist/artist3' },
            },
          ],
          album: {
            id: 'album3',
            name: 'Starlight',
            images: [],
            release_date: '2024-02-10',
            total_tracks: 14,
          },
          duration_ms: 267000,
          explicit: false,
          popularity: 76,
          preview_url: null,
          external_urls: { spotify: 'https://open.spotify.com/track/track3' },
        },
      ],
      mediumTerm: [],
      longTerm: [],
    },
    topArtists: {
      shortTerm: [
        {
          id: 'artist1',
          name: 'Crystal Waves',
          genres: ['synthwave', 'electronic'],
          popularity: 78,
          images: [],
          followers: { total: 125000 },
          external_urls: { spotify: 'https://open.spotify.com/artist/artist1' },
        },
      ],
      mediumTerm: [],
      longTerm: [],
    },
    recentlyPlayed: [],
    audioFeatures: [
      {
        id: 'track1',
        acousticness: 0.1,
        danceability: 0.78,
        duration_ms: 234000,
        energy: 0.85,
        instrumentalness: 0.2,
        key: 0,
        liveness: 0.15,
        loudness: -5.2,
        mode: 1,
        speechiness: 0.05,
        tempo: 128,
        time_signature: 4,
        valence: 0.72,
      },
    ],
    savedTracksCount: 847,
    playlists: [],
  },
  analysis: {
    geneticHelix: {
      tracks: [
        {
          track: {
            id: 'track1',
            name: 'Midnight Dreams',
            artists: [
              {
                id: 'artist1',
                name: 'Crystal Waves',
                genres: ['synthwave'],
                popularity: 78,
                images: [],
                followers: { total: 125000 },
                external_urls: { spotify: 'https://open.spotify.com/artist/artist1' },
              },
            ],
            album: {
              id: 'album1',
              name: 'Neon Visions',
              images: [],
              release_date: '2024-01-15',
              total_tracks: 12,
            },
            duration_ms: 234000,
            explicit: false,
            popularity: 84,
            preview_url: null,
            external_urls: { spotify: 'https://open.spotify.com/track/track1' },
          },
          position: {
            x: 10.5,
            y: 25.3,
            z: 0.2,
            radius: 15,
            angle: 0.5,
            helixHeight: 100,
          },
          features: {
            id: 'track1',
            acousticness: 0.1,
            danceability: 0.78,
            duration_ms: 234000,
            energy: 0.85,
            instrumentalness: 0.2,
            key: 0,
            liveness: 0.15,
            loudness: -5.2,
            mode: 1,
            speechiness: 0.05,
            tempo: 128,
            time_signature: 4,
            valence: 0.72,
          },
          color: '#FF006E',
          size: 8,
        },
      ],
      strands: {
        strandA: { name: 'Energy', feature: 'energy' },
        strandB: { name: 'Valence', feature: 'valence' },
      },
      summary: {
        averageEnergy: 0.76,
        averageValence: 0.68,
        averageDanceability: 0.72,
        averageAcousticness: 0.15,
        dominantMood: 'Energetic & Euphoric',
        dominantTempo: '120-130 BPM',
      },
    },
    timeTunnel: {
      segments: [],
      totalTracks: 847,
      timeRange: {
        start: '2024-01-01',
        end: '2024-12-31',
      },
      listeningHabits: {
        peakHours: ['22:00', '23:00', '00:00'],
        mostActiveDay: 'Friday',
        totalListeningTime: 12847,
      },
    },
    aiStory:
      'Luna navigates the cosmos through a tapestry of electronic dreams. Your taste dances between euphoric synthwave peaks and ambient valleys, a musical DNA coded in neon light and starlight. You seek rhythm in darkness, finding solace in the marriage of vintage synthesizers and modern production. Your journey through sound is one of perpetual midnight runs through digital highways, each track a beacon in your personal universe.',
    timestamp: new Date('2024-02-15'),
    summary: {
      topGenres: ['synthwave', 'electronic', 'indie', 'ambient'],
      listeningDiversity: 0.82,
      favoriteDecade: '2020s',
      discoveryScore: 0.75,
    },
  },
  metadata: {
    createdAt: new Date('2024-02-15'),
    isPublic: true,
    viewCount: 342,
  },
};
